(function(a){a.fn.hoverIntent=function(i,e){var b={sensitivity:7,interval:100,timeout:0};b=a.extend(b,e?{over:i,out:e}:i);var h,n,k,l,m=function(c){h=c.pageX;n=c.pageY},f=function(c,g){g.hoverIntent_t=clearTimeout(g.hoverIntent_t);if(Math.abs(k-h)+Math.abs(l-n)<b.sensitivity){a(g).unbind("mousemove",m);g.hoverIntent_s=1;return b.over.apply(g,[c])}else{k=h;l=n;g.hoverIntent_t=setTimeout(function(){f(c,g)},b.interval)}},d=function(c){for(var g=(c.type=="mouseover"?c.fromElement:c.toElement)||c.relatedTarget;g&&
g!=this;)try{g=g.parentNode}catch(p){g=this}if(g==this)return false;var o=jQuery.extend({},c),j=this;if(j.hoverIntent_t)j.hoverIntent_t=clearTimeout(j.hoverIntent_t);if(c.type=="mouseover"){k=o.pageX;l=o.pageY;a(j).bind("mousemove",m);if(j.hoverIntent_s!=1)j.hoverIntent_t=setTimeout(function(){f(o,j)},b.interval)}else{a(j).unbind("mousemove",m);if(j.hoverIntent_s==1)j.hoverIntent_t=setTimeout(function(){j.hoverIntent_t=clearTimeout(j.hoverIntent_t);j.hoverIntent_s=0;b.out.apply(j,[o])},b.timeout)}};
return this.mouseover(d).mouseout(d)}})(jQuery);
(function(a){a.fn.supersubs=function(i){var e=a.extend({},a.fn.supersubs.defaults,i);return this.each(function(){var b=a(this),h=a.meta?a.extend({},e,b.data()):e,n=a('<li id="menu-fontsize">&#8212;</li>').css({padding:0,position:"absolute",top:"-999em",width:"auto"}).appendTo(b).width();a("#menu-fontsize").remove();$ULs=b.find("ul");$ULs.each(function(k){k=$ULs.eq(k);var l=k.children(),m=l.children("a"),f=l.css("white-space","nowrap").css("float"),d=k.add(l).add(m).css({"float":"none",width:"auto"}).end().end()[0].clientWidth/
n;d+=h.extraWidth;if(d>h.maxWidth)d=h.maxWidth;else if(d<h.minWidth)d=h.minWidth;d+="em";k.css("width",d);l.css({"float":f,width:"100%","white-space":"normal"}).each(function(){var c=a(">ul",this),g=c.css("left")!==undefined?"left":"right";c.css(g,d)})})})};a.fn.supersubs.defaults={minWidth:9,maxWidth:25,extraWidth:0}})(jQuery);
(function(a){a.fn.superfish=function(e){var b=a.fn.superfish,h=b.c,n=a(['<span class="',h.arrowClass,'"> &#187;</span>'].join("")),k=function(){var f=a(this),d=m(f);clearTimeout(d.sfTimer);f.showSuperfishUl().siblings().hideSuperfishUl()},l=function(){var f=a(this),d=m(f),c=b.op;clearTimeout(d.sfTimer);d.sfTimer=setTimeout(function(){c.retainPath=a.inArray(f[0],c.$path)>-1;f.hideSuperfishUl();c.$path.length&&f.parents(["li.",c.hoverClass].join("")).length<1&&k.call(c.$path)},c.delay)},m=function(f){f=
f.parents(["ul.",h.menuClass,":first"].join(""))[0];b.op=b.o[f.serial];return f};return this.each(function(){var f=this.serial=b.o.length,d=a.extend({},b.defaults,e);d.$path=a("li."+d.pathClass,this).slice(0,d.pathLevels).each(function(){a(this).addClass([d.hoverClass,h.bcClass].join(" ")).filter("li:has(ul)").removeClass(d.pathClass)});b.o[f]=b.op=d;a("li:has(ul)",this)[a.fn.hoverIntent&&!d.disableHI?"hoverIntent":"hover"](k,l).each(function(){d.autoArrows&&a(">a:first-child",this).addClass(h.anchorClass).append(n.clone())}).not("."+
h.bcClass).hideSuperfishUl();var c=a("a",this);c.each(function(g){var p=c.eq(g).parents("li");c.eq(g).focus(function(){k.call(p)}).blur(function(){l.call(p)})});d.onInit.call(this)}).each(function(){var f=[h.menuClass];b.op.dropShadows&&!(a.browser.msie&&a.browser.version<7)&&f.push(h.shadowClass);a(this).addClass(f.join(" "))})};var i=a.fn.superfish;i.o=[];i.op={};i.IE7fix=function(){var e=i.op;a.browser.msie&&a.browser.version>6&&e.dropShadows&&e.animation.opacity!=undefined&&this.toggleClass(i.c.shadowClass+
"-off")};i.c={bcClass:"sf-breadcrumb",menuClass:"sf-js-enabled",anchorClass:"sf-with-ul",arrowClass:"sf-sub-indicator",shadowClass:"sf-shadow"};i.defaults={hoverClass:"sfHover",pathClass:"overideThisToUse",pathLevels:1,delay:800,animation:{opacity:"show"},speed:"normal",autoArrows:true,dropShadows:true,disableHI:false,onInit:function(){},onBeforeShow:function(){},onShow:function(){},onHide:function(){}};a.fn.extend({hideSuperfishUl:function(){var e=i.op,b=e.retainPath===true?e.$path:"";e.retainPath=
false;b=a(["li.",e.hoverClass].join(""),this).add(this).not(b).removeClass(e.hoverClass).find(">ul").hide().css("visibility","hidden");e.onHide.call(b);return this},showSuperfishUl:function(){var e=i.op,b=this.addClass(e.hoverClass).find(">ul:hidden").css("visibility","visible");i.IE7fix.call(b);e.onBeforeShow.call(b);b.animate(e.animation,e.speed,function(){i.IE7fix.call(b);e.onShow.call(b)});return this}})})(jQuery);